// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYP_sExjn6-InYOZxrBOJxe0Tkp5b0uBc',
    appId: '1:685651794501:web:5a75745e1dab10886d212c',
    messagingSenderId: '685651794501',
    projectId: 'zometo-bc04b',
    authDomain: 'zometo-bc04b.firebaseapp.com',
    databaseURL: 'https://zometo-bc04b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zometo-bc04b.appspot.com',
    measurementId: 'G-PBX7RB1C9K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEnSXnrzuyEqaTPwBu8LGpQmo-l3wKQPs',
    appId: '1:685651794501:android:7afc3dc1c895ac896d212c',
    messagingSenderId: '685651794501',
    projectId: 'zometo-bc04b',
    databaseURL: 'https://zometo-bc04b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zometo-bc04b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZlFZCmJBGiSy3zqtI3TFB9mMv0FaekNY',
    appId: '1:685651794501:ios:af9be60dbcb1dab56d212c',
    messagingSenderId: '685651794501',
    projectId: 'zometo-bc04b',
    databaseURL: 'https://zometo-bc04b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zometo-bc04b.appspot.com',
    androidClientId: '685651794501-qeh1rnejk98kidgne7dq4c7acoae54uv.apps.googleusercontent.com',
    iosClientId: '685651794501-u22ug0veffesehjpmki2glkab12ujhb7.apps.googleusercontent.com',
    iosBundleId: 'zometo',
  );
}
